name: Datadog Stats
description: Collects detailed stats on build times and outcomes and sends to datadog
author: https://github.com/better
requirements:
  - buildkite-agent
configuration:
  properties:
    pattern:
      name: string
  required:
    - pattern
  additionalProperties: false
