name: Datadog Stats
description: Collects detailed stats on build times and outcomes and sends to datadog
author: https://github.com/better
requirements:
  - buildkite-agent
  - nc
configuration:
  properties:
    dogstatsd_host:
      type: string
    dogstatsd_port:
      type: string
  required:
    - dogstatsd_host
  additionalProperties: false
